### ISSUE TITLE
Payment for Live client not going through

### ISSUE THREAD

**Issue by ShawnCholeva** [erksch/react-smart-payment-buttons#9]
Hey I am not sure if this is a paypal issue or something here but I thought I would start here.  So the button and everything rendered great and the implementation was really simple.. thank you!  But I am having an issue with the payment processing.

I tried the button out with my sandbox account and everything went well, and then I tried in live with my live ClientId and it brings up the popup and lets me go through making a payment, but when I finish making the payment, the popup goes away and I am not seeing any transactions in the payee or my business account.  I have done this 3 times, either via the paypal button or a debit card button.. each for 1$, and noticed that one of the times I got the following email.

![image](https://user-images.githubusercontent.com/13332685/66163593-50b0f280-e5f6-11e9-997c-7fe7b706760b.png)

I would assume there is no need to confirm, and my website has no way to confirm the payment.  Have you experienced anything like this?  I went through the documentation but am not seeing anything related to confirmations.  I am a little confused because it worked so well in the sandbox, but I am thinking this may have something to do with how I have Paypal set up too as I just created the account not long ago.

I am using the `REACT_APP_PAYPAL_CLIENT_ID` to provide my sandbox and live id based on my environment.  The way I have implemented this is as follows:

```
class PayPalButtons extends React.Component<Props> {
  renderButton = () => (
    <SmartPaymentButtons
      style={{ color: "blue" }}
      loading={<CircularProgress />}
      createOrder={(_data: any, actions: any) => {
        return actions.order.create({
          purchase_units: [
            {
              amount: {
                value: this.props.amount || 10
              }
            }
          ]
        });
      }}
      onApprove={() => {
        this.props.enqueueSnackbar({
          message: 'Success!',
        });
      }}
      onError={() => {
        this.props.enqueueSnackbar({
          message: 'Error!',
        });
      }}
    />
  );
  render() {
    return <PayPalSDKWrapper>{this.renderButton()}</PayPalSDKWrapper>;
  }
}
```

And in the onAprrove, I am getting back the data param like so (I modified the orderID and payerId);

```
billingToken: null
orderID: "1YH66346345610333G995864S2"
payerID: "TESDT7G44UHH56D5R9X9Q"
paymentID: null
```

**Comment by erksch** [comment]
Hmm weird, have you applied the `clientID` attribute to the `PayPalSDKWrapper` component? It's missing in your code. Mind that when using the `PayPalSDKWrapper`, you don't need the `<script>` import of the paypal SDK anymore. 

But I'll take a look into my production code and get back to you!

**Comment by erksch** [comment]
Okay! I'd say you forgot to capture the transaction in your `onApprove` callback. 
Take a look in the PayPal docs [here](https://developer.paypal.com/docs/checkout/integrate/#5-capture-the-transaction).

**Comment by ShawnCholeva** [comment]
That was exactly the problem, will mark this as closed.  Thanks for the fast response time and reference to their docs!

**Comment by erksch** [comment]
No problem have a good day!
